name: mealapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

  # Firebase services
  firebase_auth:
  firebase_core:
  cloud_firestore: ^5.6.5

  # UI and animations
  flutter_svg:

  # State management and architecture
  flutter_bloc:
  dartz:
  equatable: ^2.0.7

  # Dependency injection
  get_it:

  # Navigation
  go_router: ^14.8.1

  # Local database (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Internet connection checking
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/categories/
    - assets/images/meals/
    - assets/images/splash/