name: mealapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_auth:
  firebase_core:
  cloud_firestore: ^5.6.5
  flutter_svg:
  flutter_bloc:
  dartz:
  get_it:
  equatable: ^2.0.7
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/categories/
    - assets/images/meals/
    - assets/images/splash/