// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm_yESUx2TY7bmPFcWGvYmzIkWdVUAK-Q',
    appId: '1:297336185214:web:d558f3627a7a2cf3f2132f',
    messagingSenderId: '297336185214',
    projectId: 'ecommerce-2456i32ffd',
    authDomain: 'ecommerce-2456i32ffd.firebaseapp.com',
    storageBucket: 'ecommerce-2456i32ffd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-MdIPj4L5KrJ0j9c-OskCidGg-4qhIw',
    appId: '1:297336185214:android:6168da825178cf99f2132f',
    messagingSenderId: '297336185214',
    projectId: 'ecommerce-2456i32ffd',
    storageBucket: 'ecommerce-2456i32ffd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81Ap_vrwFuuVqDwGvFdox_ZFeLTG2uGQ',
    appId: '1:297336185214:ios:038e1df5f1fdb2a6f2132f',
    messagingSenderId: '297336185214',
    projectId: 'ecommerce-2456i32ffd',
    storageBucket: 'ecommerce-2456i32ffd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81Ap_vrwFuuVqDwGvFdox_ZFeLTG2uGQ',
    appId: '1:297336185214:ios:038e1df5f1fdb2a6f2132f',
    messagingSenderId: '297336185214',
    projectId: 'ecommerce-2456i32ffd',
    storageBucket: 'ecommerce-2456i32ffd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm_yESUx2TY7bmPFcWGvYmzIkWdVUAK-Q',
    appId: '1:297336185214:web:b32d1e084d9b1820f2132f',
    messagingSenderId: '297336185214',
    projectId: 'ecommerce-2456i32ffd',
    authDomain: 'ecommerce-2456i32ffd.firebaseapp.com',
    storageBucket: 'ecommerce-2456i32ffd.firebasestorage.app',
  );
}
